// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-oWkUCMLftAOqQw0pp80BMPg8PBPYLKU',
    appId: '1:259276980419:web:8b84b8b5c4bc0e6b7ee276',
    messagingSenderId: '259276980419',
    projectId: 'recipesappflutter-76319',
    authDomain: 'recipesappflutter-76319.firebaseapp.com',
    storageBucket: 'recipesappflutter-76319.firebasestorage.app',
    measurementId: 'G-6QNBQC1M1B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2cu9neG_jpFgxolIJ6bBJu4GShWLbCgQ',
    appId: '1:259276980419:android:3989ed81b516364e7ee276',
    messagingSenderId: '259276980419',
    projectId: 'recipesappflutter-76319',
    storageBucket: 'recipesappflutter-76319.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-oWkUCMLftAOqQw0pp80BMPg8PBPYLKU',
    appId: '1:259276980419:web:e9613a1d309bce547ee276',
    messagingSenderId: '259276980419',
    projectId: 'recipesappflutter-76319',
    authDomain: 'recipesappflutter-76319.firebaseapp.com',
    storageBucket: 'recipesappflutter-76319.firebasestorage.app',
    measurementId: 'G-SHTX54KFR4',
  );
}
